# Generated by Django 5.0.6 on 2024-06-23 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloggers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('comments_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bloggers.bloggermodel')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
