# Generated by Django 5.0.6 on 2024-06-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
