# Generated by Django 5.0.6 on 2024-06-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentmodel_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='commet_date',
            new_name='comment_date',
        ),
    ]
