# Generated by Django 5.0.6 on 2024-06-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggermodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
